sudo: required
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  -  chmod -r 755 ./node_modules/.bin/hexo
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "DcmTruman"
  - git config user.email "695897983@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git pull --rebase origin master
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/DcmTruman/DcmTruman.github.io.git
